apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "ejbca-csr-signer.clusterRole" . }}-binding
  labels:
    {{- include "ejbca-csr-signer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "ejbca-csr-signer.clusterRole" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ejbca-csr-signer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "ejbca-csr-signer.role" . }}-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ejbca-csr-signer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "ejbca-csr-signer.role" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "ejbca-csr-signer.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
---