apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "ejbca-csr-signer.role" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ejbca-csr-signer.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "get", "watch", "list", "update", "delete"]